AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Obtém do sqs o novo pré-usuário, cadastra no dynamodb e envia o email de
  validação para o usuário
Resources:
  createprecustomer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Obtém do sqs o novo pré-usuário, cadastra no dynamodb e envia o email de
        validação para o usuário
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::297738258633:role/LambdaFunctionsRole'
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
        SQS2:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue2
                - Arn
            BatchSize: 10
      VpcConfig:
        SecurityGroupIds:
          - sg-03ed5bdb6048d0544
        SubnetIds:
          - subnet-0448a35c96f4a061f
          - subnet-0b5901f76345dc1a8
      Environment:
        Variables:
          EMAIL_SENDER: 'https://sqs.sa-east-1.amazonaws.com/297738258633/email-sender'
          TABLE_NAME: pre-customer
      Layers:
        - 'arn:aws:lambda:sa-east-1:297738258633:layer:utils:20'
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  SQSQueue2:
    Type: 'AWS::SQS::Queue'
    Properties: {}
